level._custom_perks tree 
    array perk_name 
        property alias 
        property cost 
        property hint_string
        property perk_bottle 
        property perk_machine_set_kvps
        property perk_machine_thread 
        property precache_func 
        property player_thread_give 
        property player_thread_take 
        property clientfield_register
        property clientfield_set 